name: job_seeker_for_you
description: JobSeeker – oferty pracy, ulubione, powiadomienia, mapa OSM
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: 0.13.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  connectivity_plus: ^3.0.3
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.4

  # Mapy OSM
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geocoding: ^4.0.0

  # UI helpers
  intl: ^0.19.0
  url_launcher: ^6.3.0
  file_picker: ^8.0.7
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
